name: Code quality check

on: push

jobs:
  lint:
    name: Code quality check
    runs-on: ubuntu-24.04
    container: python:3.10.12
    services:
      postgres:
        image: postgres:14.7-alpine
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: warehouse
          POSTGRES_PASSWORD: warehouse
          POSTGRES_DB: warehouse
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache nox and deps
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: |
            .cache/pip
            .nox/hooks
          key: nox-hooks-${{ hashFiles('**/poetry.lock') }}
          restore-keys: nox-hooks-

      - name: Install nox
        run: pip install nox

      - name: Code quality check
        run: nox --session hooks
